# Generated by Django 5.2.9 on 2025-12-25 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('risk_type', models.CharField(choices=[('flood', 'Inondation'), ('earthquake', 'Séisme'), ('landslide', 'Glissement de terrain'), ('drought', 'Sécheresse'), ('fire', 'Incendie'), ('storm', 'Tempête'), ('volcano', 'Volcan')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('area_coordinates', models.JSONField(blank=True, help_text='Coordonnées de la zone en format GeoJSON', null=True)),
                ('preventive_actions', models.TextField(blank=True, help_text='Actions préventives recommandées')),
                ('emergency_contacts', models.JSONField(blank=True, default=list, help_text="Contacts d'urgence")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-risk_level', 'name'],
                'indexes': [models.Index(fields=['risk_type', 'risk_level'], name='maps_riskzo_risk_ty_3e43d9_idx'), models.Index(fields=['latitude', 'longitude'], name='maps_riskzo_latitud_7d5146_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('warning', 'Avertissement'), ('watch', 'Vigilance'), ('emergency', 'Urgence')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('risk_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='maps.riskzone')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['active', '-issued_at'], name='maps_alert_active_693445_idx')],
            },
        ),
    ]
